repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
