# Google settings...
PATH_CREDENTIALS = ""
PATH_TOKEN = ""
SERVICE_ACCOUNT = ""

SPREADSHEET_ID = ""

# Sophia settings...
SOPHIA_ACCESS = {"usuario"="", "senha"=""}

POST_AUTH = ""
GET_STUDENTS = ""
GET_STUDENT = ""
PUT_STUDENTS = ""
GET_CLASSROOM = ""
