# Google secrets settings...

PATH_CREDENTIALS = "C:\\Development\\Projects\\new_sgap\\credentials.json"
SERVICE_ACCOUNT = "francisco.duo@portalcci.com.br"

# Sophia secrets settings...

SOPHIA_ACCESS = {"usuario"="setape", "senha"="setape"}

# Url of auth

POST_AUTH = "https://portal.sophia.com.br/SophiAWebAPI/3055/api/v1/Autenticacao"
GET_STUDENTS = "https://portal.sophia.com.br/SophiAWebAPI/3055/api/v1/Alunos"
GET_CLASSROOM = "https://portal.sophia.com.br/SophiAWebAPI/3055/api/v1/Turmas"
